<script type="text/x-magento-init">
{
"*": {
        "mySlider": {
            "selector": ".gallery__slider",
            "dots": true,
            "slidesToShow": 3,
            "slidesToScroll": 1,
            "infinite": true,
            "arrows": false,
            "autoplay": false,
            "responsive": [
                {
                    "breakpoint": 650,
                    "settings": {
                        "slidesToShow": 2,
                        "slidesToScroll": 1
                    }
                },
                {
                    "breakpoint": 500,
                    "settings": {
                        "slidesToShow": 1,
                        "slidesToScroll": 1
                    }
                }
            ]
        }
    }
}
</script>

