
        <script type="text/x-magento-init">
        {
            ".toolbar-sorter": {
                "mySelect": {
                    "template": "#sorter"
                }
            },
            ".toolbar-products": {
                "mySelect": {
                    "template": ".limiter-options"
                }
            },
            ".sidebar":{
                "mySlider": {
                    "selector": ".sidebar-slider",
                    "dots": true,
                    "slidesToScroll": 1,
                    "infinite": true,
                    "autoplay": true
                }
            },
            ".footer__links": {
                "footerCollapse": {}

            }
        }
        </script>