
        <script type="text/x-magento-init">
        {
            ".toolbar-sorter": {
                "mySelect": {
                    "template": "#sorter"
                }
            },
            ".toolbar-products": {
                "mySelect": {
                    "template": ".limiter-options"
                }
            }
        }
        </script>

        <script type="text/x-magento-init">
        {
            ".footer__links": {
                "footerCollapse": {}
            }
        }
        </script>